# Dependencies
markdown:         redcarpet
highlighter:      pygments
# pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Salman Wahed's blog
tagline:          ''
description:      'Technical Writings'
url:              http://salmanwahed.github.io

author:
  name:           'Salman Wahed'
  url:            https://twitter.com/salman_wahed

paginate:         2

# Custom vars
version:          3.0.0

github:
  repo:           https://github.com/salmanwahed/salmanwahed.github.io


# Social links
twitter_username:     salman_wahed
github_username:      salmanwahed
linkedin_username:    salmanwahed
google_plus_username: +SalmanWahed
facebook_username:    salmanwahed
stack_overflow_username: salmanwahed
