# Dependencies
markdown:         redcarpet
# highlighter:         true
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Salman Wahed's blog
tagline:          ''
description:      'Technical Writings'
url:              http://salmanwahed.github.io

author:
  name:           'Salman Wahed'
  url:            https://twitter.com/salman_wahed

paginate:         1

# Custom vars
version:          3.0.0

github:
  repo:           https://github.com/salmanwahed/salmanwahed.github.io
